
import java.awt.event.KeyEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtITC = new javax.swing.JTextField();
        txtITF = new javax.swing.JTextField();
        txtP1 = new javax.swing.JTextField();
        txtMMW = new javax.swing.JTextField();
        txtppc = new javax.swing.JTextField();
        txtUTS = new javax.swing.JTextField();
        txtGMRC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlblavg = new javax.swing.JLabel();
        jlblgpa = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnCalc1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("STUDENT GRADES");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Student Name:");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Programming 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("IT Fundamentals");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Intro to Computing");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mathematics in the Modern World");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Purposive Communication");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Understanding the Self");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Good Manners and Right Conduct");

        txtITC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtITC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtITC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtITCActionPerformed(evt);
            }
        });
        txtITC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtITCKeyTyped(evt);
            }
        });

        txtITF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtITF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtITF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtITFActionPerformed(evt);
            }
        });
        txtITF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtITFKeyTyped(evt);
            }
        });

        txtP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtP1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP1.setActionCommand("<Not Set>");
        txtP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP1ActionPerformed(evt);
            }
        });
        txtP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtP1KeyTyped(evt);
            }
        });

        txtMMW.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMMW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMMWActionPerformed(evt);
            }
        });
        txtMMW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMMWKeyTyped(evt);
            }
        });

        txtppc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtppc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtppc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtppcActionPerformed(evt);
            }
        });
        txtppc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtppcKeyTyped(evt);
            }
        });

        txtUTS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtUTS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUTSActionPerformed(evt);
            }
        });
        txtUTS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUTSKeyTyped(evt);
            }
        });

        txtGMRC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtGMRC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGMRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGMRCActionPerformed(evt);
            }
        });
        txtGMRC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGMRCKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Grade Points");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setForeground(new java.awt.Color(255, 0, 0));
        jlblTotal.setText("TOTAL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("AVG");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("GPA");

        jlblavg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblavg.setForeground(new java.awt.Color(255, 0, 0));
        jlblavg.setText("AVG");

        jlblgpa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblgpa.setForeground(new java.awt.Color(255, 0, 0));
        jlblgpa.setText("GPA");

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("RESET");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCalc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalc1.setText("Calculate");
        btnCalc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalc1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtP1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtITC)
                            .addComponent(txtITF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtGMRC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMMW))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(82, 82, 82)
                            .addComponent(txtppc))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(111, 111, 111)
                            .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblgpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(262, 262, 262))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlblavg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(484, Short.MAX_VALUE)
                    .addComponent(btnCalc1)
                    .addGap(152, 152, 152)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtITC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtITF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtppc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGMRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jlblTotal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jlblavg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlblgpa))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(480, Short.MAX_VALUE)
                    .addComponent(btnCalc1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)))
        );

        txtName.getAccessibleContext().setAccessibleParent(txtName);
        txtITC.getAccessibleContext().setAccessibleParent(txtITC);
        txtITF.getAccessibleContext().setAccessibleParent(txtITF);
        txtP1.getAccessibleContext().setAccessibleParent(txtP1);
        txtMMW.getAccessibleContext().setAccessibleParent(txtMMW);
        txtppc.getAccessibleContext().setAccessibleDescription("");
        txtppc.getAccessibleContext().setAccessibleParent(txtppc);
        txtUTS.getAccessibleContext().setAccessibleParent(txtUTS);
        txtGMRC.getAccessibleContext().setAccessibleParent(txtGMRC);
        jlblTotal.getAccessibleContext().setAccessibleParent(jlblTotal);
        jlblavg.getAccessibleContext().setAccessibleParent(jlblavg);
        jlblgpa.getAccessibleContext().setAccessibleParent(jlblgpa);
        btnClear.getAccessibleContext().setAccessibleParent(btnClear);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtITCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtITCActionPerformed
   
    }//GEN-LAST:event_txtITCActionPerformed

    private void txtITFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtITFActionPerformed
     
    }//GEN-LAST:event_txtITFActionPerformed

    private void txtP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP1ActionPerformed

    private void txtMMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMMWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMMWActionPerformed

    private void txtppcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtppcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtppcActionPerformed

    private void txtUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUTSActionPerformed

    private void txtGMRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGMRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGMRCActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtName.setText(null);
        txtP1.setText(null);
        txtITC.setText(null); //RESET BUTTON
        txtITF.setText(null);
        txtMMW.setText(null);
        txtppc.setText(null);
        txtUTS.setText(null);
        txtGMRC.setText(null);
        jlblTotal.setText(null);
        jlblavg.setText(null);
        jlblgpa.setText(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalc1ActionPerformed
        double p1,itc,itf,mmw,ppc,uts,gmrc,tot,avg; //VARIABLE SHORTCUT NAMES
        String gpa; //TOTAL GPA 
        
        p1 = Double.parseDouble(txtP1.getText());
        itc = Double.parseDouble(txtITC.getText());
        itf = Double.parseDouble(txtITF.getText());
        mmw = Double.parseDouble(txtMMW.getText());
        ppc = Double.parseDouble(txtppc.getText());
        uts = Double.parseDouble(txtUTS.getText());
        gmrc = Double.parseDouble(txtGMRC.getText());
         
        tot = p1 + itc + itf + mmw + ppc + uts + gmrc;
        avg = tot/7; //SUBJECT NAMES
        
        if(avg >= 95) //GRADE FORMULA?
        {
            gpa = "1.5";
        }
        else if(avg >= 89)
        {
            gpa = "2.5";
        }
        else if(avg >= 79)
        {
            gpa = "2.6";
        }
        else if(avg >= 75)
        {
            gpa = "3.0";
        }
        else 
        {
            gpa = "5.0";
        }
        
        jlblTotal.setText(String.valueOf(tot));
        jlblavg.setText(String.valueOf(avg));
        jlblgpa.setText(gpa);
    }//GEN-LAST:event_btnCalc1ActionPerformed

    private void txtP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtP1KeyTyped
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtP1KeyTyped

    private void txtITCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtITCKeyTyped
           char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtITCKeyTyped

    private void txtITFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtITFKeyTyped
           char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtITFKeyTyped

    private void txtMMWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMMWKeyTyped
           char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtMMWKeyTyped

    private void txtppcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtppcKeyTyped
           char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtppcKeyTyped

    private void txtUTSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUTSKeyTyped
           char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtUTSKeyTyped

    private void txtGMRCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGMRCKeyTyped
            char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber ==KeyEvent.VK_BACK_SPACE)
                    ||(iNumber ==KeyEvent.VK_DELETE)){
        evt.consume();
    }
    }//GEN-LAST:event_txtGMRCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc1;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblavg;
    private javax.swing.JLabel jlblgpa;
    private javax.swing.JTextField txtGMRC;
    private javax.swing.JTextField txtITC;
    private javax.swing.JTextField txtITF;
    private javax.swing.JTextField txtMMW;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtUTS;
    private javax.swing.JTextField txtppc;
    // End of variables declaration//GEN-END:variables
}
